server:
  port: 8080

spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:default;INIT=runscript from 'src/test/resources/initTest.sql';MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect